apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  serviceName: "kafka"
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.4
        command: ["bash", "-c", "unset KAFKA_PORT; /etc/confluent/docker/run"]
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://0.0.0.0:9092 # Add external listener
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://a846a4b09fe0c4221b5be54612cc16db-1126670917.eu-west-2.elb.amazonaws.com:9092 # Update with correct service DNS and external IP/port
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT # Add security protocol for EXTERNAL listener
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: PLAINTEXT
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-0.zookeeper:2181
          - name: KAFKA_BROKER_ID
            value: "0"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"


---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9092
  type: LoadBalancer
#  externalIPs: 
#    - 192.168.0.10

