apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-0
  labels:
    type: local
spec:
  storageClassName: ebs-sc
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"