

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-api-doc
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
      worker_connections  10240;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
                      
      access_log  /var/log/nginx/access.log  main;
      
      sendfile        on;
      keepalive_timeout  65;

      server {
          listen 4400;
          server_name  localhost;
          root /usr/share/nginx/html;
          index index.html;
          location / {
            try_files $uri $uri/ /index.html;
        }
      }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-doc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-doc
  template:
    metadata:
      labels:
        app: api-doc
    spec:
      imagePullSecrets:
      - name: test-secret
      containers:
      - name: api-doc
        image: 844605633964.dkr.ecr.eu-west-2.amazonaws.com/aig-api-documentation-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4400
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
           name: nginx-config-api-doc
---

apiVersion: v1
kind: Service
metadata:
  name: api-doc-service
spec:
  selector:
    app: api-doc
  ports:
    - protocol: TCP
      port: 4400
      targetPort: 4400
  type: LoadBalancer
